[package]
name = "aaadaw-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
audio-device = ["aaadaw-engine/audio-device"]
jack-backend = ["audio-device", "aaadaw-engine/jack-backend"]
pipewire-backend = ["audio-device", "aaadaw-engine/pipewire-backend"]
wasapi-backend = ["audio-device", "aaadaw-engine/wasapi-backend"]

[dependencies]
aaadaw-core = { path = "../aaadaw-core" }
aaadaw-engine = { path = "../aaadaw-engine" }
aaadaw-media = { path = "../aaadaw-media" }
aaadaw-storage = { path = "../aaadaw-storage" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
