[package]
name = "aaadaw-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aaadaw-core = { path = "../aaadaw-core" }
aaadaw-engine = { path = "../aaadaw-engine" }
symphonia = { version = "0.6.1", default-features = false, features = ["aac", "flac", "mp3", "ogg", "pcm", "vorbis", "wav", "isomp4"] }
