[package]
name = "aaadaw-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
jack-backend = ["dep:jack"]
pipewire-backend = ["dep:pipewire"]

[dependencies]
aaadaw-core = { path = "../aaadaw-core" }
jack = { version = "0.13.5", optional = true }
pipewire = { version = "0.10", optional = true }
rtrb = "0.4.0"
