[package]
name = "aaadaw"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
jack-backend = ["aaadaw-app/jack-backend"]

[dependencies]
aaadaw-core = { path = "../aaadaw-core" }
aaadaw-app = { path = "../aaadaw-app" }
aaadaw-storage = { path = "../aaadaw-storage" }
rfd = "0.15.4"
iced = { version = "0.14.0", default-features = false, features = ["tiny-skia", "x11", "wayland", "tokio", "linux-theme-detection"] }
