[package]
name = "aaadaw"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
jack-backend = ["aaadaw-app/jack-backend"]
pipewire-backend = ["aaadaw-app/pipewire-backend"]

[dependencies]
aaadaw-core = { path = "../aaadaw-core" }
aaadaw-app = { path = "../aaadaw-app" }
aaadaw-media = { path = "../aaadaw-media" }
aaadaw-storage = { path = "../aaadaw-storage" }
aaadaw-engine = { path = "../aaadaw-engine" }
rfd = "0.15.4"
iced = { version = "0.14.0", default-features = false, features = ["wgpu", "canvas", "advanced", "x11", "wayland", "tokio", "linux-theme-detection"] }
bytemuck = { version = "1.24", features = ["derive"] }
x11rb = "0.13.2"
