-- Run only in a new disposable project with an isolated REAPER configuration.
local root=assert(os.getenv("AAADAW_REAPER_PROBE_DIR"), "Set AAADAW_REAPER_PROBE_DIR").."/"
assert(reaper.CountTracks(0)==0, "Routing probe requires an empty disposable project")
local function track(name,file)
 reaper.InsertTrackAtIndex(reaper.CountTracks(0),true)
 local t=reaper.GetTrack(0,reaper.CountTracks(0)-1)
 reaper.GetSetMediaTrackInfo_String(t,"P_NAME",name,true)
 local i=reaper.AddMediaItemToTrack(t)
 local take=reaper.AddTakeToMediaItem(i)
 reaper.SetMediaItemTake_Source(take,reaper.PCM_Source_CreateFromFile(root..file..".wav"))
 reaper.SetMediaItemInfo_Value(i,"D_LENGTH",1)
 reaper.SetMediaItemInfo_Value(i,"D_FADEINLEN",0)
 reaper.SetMediaItemInfo_Value(i,"D_FADEOUTLEN",0)
 return t
end
local outer=track("Outer", "receiver")
reaper.InsertTrackAtIndex(reaper.CountTracks(0),true)
local inner=reaper.GetTrack(0,1)
reaper.GetSetMediaTrackInfo_String(inner,"P_NAME","Inner",true)
local leaf=track("Leaf", "source")
local sibling=track("Sibling", "source")
reaper.InsertTrackAtIndex(reaper.CountTracks(0),true)
local outside=reaper.GetTrack(0,4)
reaper.GetSetMediaTrackInfo_String(outside,"P_NAME","Outside",true)
reaper.SetMediaTrackInfo_Value(outer,"I_FOLDERDEPTH",1)
reaper.SetMediaTrackInfo_Value(inner,"I_FOLDERDEPTH",1)
reaper.SetMediaTrackInfo_Value(leaf,"I_FOLDERDEPTH",-1)
reaper.SetMediaTrackInfo_Value(sibling,"I_FOLDERDEPTH",-1)
local log=assert(io.open(root.."folders-reference.txt","w"))
for i=0,4 do
 local t=reaper.GetTrack(0,i)
 local _,name=reaper.GetTrackName(t)
 local p=reaper.GetParentTrack(t)
 local parent="Master"
 if p then _,parent=reaper.GetTrackName(p) end
 log:write(name.." parent="..parent.." main="..reaper.GetMediaTrackInfo_Value(t,"B_MAINSEND").." compact="..reaper.GetMediaTrackInfo_Value(t,"I_FOLDERCOMPACT").."\n")
end
log:close()
reaper.GetSetProjectInfo(0,"RENDER_BOUNDSFLAG",0,true)
reaper.GetSetProjectInfo(0,"RENDER_STARTPOS",0,true)
reaper.GetSetProjectInfo(0,"RENDER_ENDPOS",1,true)
reaper.GetSetProjectInfo(0,"RENDER_SRATE",48000,true)
reaper.GetSetProjectInfo(0,"RENDER_CHANNELS",2,true)
reaper.GetSetProjectInfo(0,"RENDER_TAILFLAG",0,true)
reaper.GetSetProjectInfo_String(0,"RENDER_FILE",root,true)
local function render(name)
 reaper.GetSetProjectInfo_String(0,"RENDER_PATTERN",name,true)
 reaper.Main_OnCommand(42230,0)
end
render("folder-nested")
reaper.SetMediaTrackInfo_Value(inner,"B_MAINSEND",0)
render("folder-parent-disabled")
reaper.SetMediaTrackInfo_Value(inner,"B_MAINSEND",1)
reaper.SetMediaTrackInfo_Value(inner,"I_SOLO",2)
render("folder-solo-inner")
reaper.SetMediaTrackInfo_Value(inner,"I_SOLO",0)
reaper.SetMediaTrackInfo_Value(leaf,"I_SOLO",2)
render("folder-solo-leaf")
reaper.SetMediaTrackInfo_Value(leaf,"I_SOLO",0)
reaper.SetMediaTrackInfo_Value(outer,"I_SOLO",2)
render("folder-solo-outer")
